/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CoralButton: typeof import('./components/Coral-Button.vue')['default']
    ReButtonSrcReButton: typeof import('./components/re-button/src/re-button.vue')['default']
  }
}
