name: Check

# 触发条件：定义工作流程的触发事件
on:
  push:
    branches:
      # 推送到main分支时触发
      - main

  pull_request:
    branches:
      # 对main分支发起Pull Request时触发
      - main

# 定义工作流中的作业
jobs:
  # 代码检查和构建合并作业
  check-and-build:
    # 测试矩阵配置：只在不同操作系统运行同一任务，减少总任务数
    strategy:
      matrix:
        # 只使用Node.js 20.x版本
        node_version: [20.x]
        # 在不同操作系统上测试，保持操作系统多样性
        os: [ubuntu-latest, windows-latest, macos-latest]
      # 允许部分任务失败而不影响其他任务
      fail-fast: false

    # 运行环境，使用测试矩阵中定义的操作系统
    runs-on: ${{ matrix.os }}

    # 任务超时时间
    timeout-minutes: 15

    # 执行步骤
    steps:
      # 配置Git行尾处理，解决不同操作系统的换行符问题
      - run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # 检出代码
      - uses: actions/checkout@v4

      # 设置PNPM
      - uses: pnpm/action-setup@v4

      # 设置Node.js环境
      - uses: actions/setup-node@v4
        with:
          # 使用矩阵中指定的Node.js版本
          node-version: ${{ matrix.node_version }}
          # 启用PNPM缓存
          cache: pnpm

      # 安装依赖
      - run: pnpm i

      # 运行代码风格检查
      - name: Run Lint
        run: pnpm run lint

      # 运行TypeScript类型检查
      - name: Run Type Check
        run: pnpm run type-check

      # 运行标准构建 - 简化构建过程，只运行一个标准构建命令
      - name: Run Build
        run: pnpm run build
